data_root: /data/Postech/data/injected_psf_kmtnet_20230925
meta_path: ./data/meta_random_injection.csv
test_data_root: /data/Postech/data/test
test_meta_path: /data/Postech/data/test/meta.csv
channels: [ref, new, sub]
normalize: min_max
imsize: 51